version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Setup Variables
          command: |
            echo 'export TAG=1.0.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=gopizza' >> $BASH_ENV 

      - setup_remote_docker:
          docker_layer_caching:false 
      - run:
          name: Build and push Docker image
          command: |
            . helloworld/bin/activate
            pyinstaller -F hello_world.py
            docker build -t patrimoo08/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push patrimoo08/$IMAGE_NAME:$TAG
 
